### PR TITLE
Updates & Improvements

### PR DESCRIPTION
**Pull request by felixbuenemann**
This is quite a big collection of improvements:
- Updates all gems to release versions
- Fix Rails 4 deprecations
- Switch from postgres to sqlite3 (easier setup for a demo app)
- Adds turbolinks and conditional get to show that it works fine with sync
- Add sync to projects list
- Handle project form via js
- Add validations for project and todo model
- Some styling fixes and better bootstrap integration

I can break this down into smaller PRs if needed.

### CODE REVIEW

**Comment by felixbuenemann** [comment]
Btw. I also found a way to run sync inside the main rails app: 4c90697810d5e6a8b2a1d4084c6879210c960ea0
It uses internal messaging instead of http for publishing and works fine for me on thin, puma and passenger standalone. Theoretically it should also work with rainbows, but it didn't work for me.

**Comment by wursttheke** [comment]
@chrismccord: Could you merge this before I'll start working on updating the example app for the upcoming 0.3.0 release? It runs perfectly on my machine. Everything seems to be fine. It would be a shame to burry this PR in oblivion. 

https://github.com/chrismccord/sync/pull/95

Viele Grüße an @felixbuenemann :)

**Comment by chrismccord** [comment]
Done! Nice work @felixbuenemann. My apologies for letting this hang for so long. Thanks!

**Comment by felixbuenemann** [comment]
Thanks to both of you for taking the time to review and merge. Sync is a great tool to simplify page updates especially in heavily asynchronous apps.

**Pull request merged**
